import Hero from "@/components/hero/hero";

export default function page() {
  return (
    <div>
      Home Page
      <Hero />
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
      <p>ok</p>
    </div>
  );
}
